#!/usr/bin/with-contenv bash

# Fetch pgdvs or update existing pgdvs
if [[ ! -d /u01/pgdvs/.git ]]; then
  echo '-----------------------'
  echo '| Installing pgdvs    |'
  echo '-----------------------'
  git clone -b master https://github.com/hectorcamp/teste /u01/pgdvs
elif [[ -d /u01/pgdvs/.git ]]; then
  echo '-----------------------'
  echo '|  Updating pgdvs  |'
  echo '-----------------------'
  cd /u01/pgdvs/ || return
  git reset --hard origin/master
  git pull --rebase
fi

# Set Permissions
chown -R abc:abc \
	/u01
